// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_auth/firebase_auth.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUdg1GiRoezsAOkdSXmNGkowmBdfxy3Uc',
    appId: '1:326156519172:web:58cad76ca847fb87203251',
    messagingSenderId: '326156519172',
    projectId: 'travlore-a1c3e',
    authDomain: 'travlore-a1c3e.firebaseapp.com',
    storageBucket: 'travlore-a1c3e.appspot.com',
    measurementId: 'G-C5FL5Y0HW2',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUdg1GiRoezsAOkdSXmNGkowmBdfxy3Uc',
    appId: '1:326156519172:web:58cad76ca847fb87203251',
    messagingSenderId: '326156519172',
    projectId: 'travlore-a1c3e',
    authDomain: 'travlore-a1c3e.firebaseapp.com',
    storageBucket: 'travlore-a1c3e.appspot.com',
    measurementId: 'G-C5FL5Y0HW2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJwMqpxKiSVfl0Ot9cDGnYi7FIQpMPdSU',
    appId: '1:326156519172:ios:3ab9a69811d5ce30203251',
    messagingSenderId: '326156519172',
    projectId: 'travlore-a1c3e',
    storageBucket: 'travlore-a1c3e.appspot.com',
    iosBundleId: 'edu.cpp.cs4750.travlore.travloreApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJwMqpxKiSVfl0Ot9cDGnYi7FIQpMPdSU',
    appId: '1:326156519172:ios:3ab9a69811d5ce30203251',
    messagingSenderId: '326156519172',
    projectId: 'travlore-a1c3e',
    storageBucket: 'travlore-a1c3e.appspot.com',
    iosBundleId: 'edu.cpp.cs4750.travlore.travloreApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaSZoN4i-GZ2pPSKn3Kt-wtDiwQHpQ9oQ',
    appId: '1:326156519172:android:2c18d2931fdb1180203251',
    messagingSenderId: '326156519172',
    projectId: 'travlore-a1c3e',
    storageBucket: 'travlore-a1c3e.appspot.com',
  );

}